version: '3.8'
services:
    service-1:
        container_name: service-1
        image: aljoco/service-1:latest
        build: ./service-1
        ports:
        - published: 5000
          target: 5000
          protocol: tcp
    service-2:
        container_name: service-2
        image: aljoco/service-2:latest
        build: ./service-2
    service-3:
        container_name: service-3
        image: aljoco/service-3:latest
        build: ./service-3
    service-4:
        container_name: service-4
        image: aljoco/service-4:latest
        build: ./service-4