version: "3.8"
services:
    service-1:
        container_name: service-1
        image: 
        build: ./service-1
        deploy:
            replicas: 4
        ports:
        - published: 5000
          target: 5000
          protocol: tcp
    service-2:
        container_name: service-2
        image: 
        build: ./service-2
        deploy:
            replicas: 4
    service-3:
        container_name: service-3
        image: 
        build: ./service-3
        deploy:
            replicas: 4